#!/usr/bin/env bash
# Writes the nginx configuration of the site, which is served through Cloudflare. Run as root:
#
#   sudo bash setup-nginx.sh test.example.org                 # test domain, before the switch
#   sudo bash setup-nginx.sh www.adoptii-animale-hope.org     # at the switch
#
# Cloudflare holds the public certificate. Between Cloudflare and this server:
#   - with a Cloudflare Origin Certificate in /etc/ssl/hope/origin.pem and origin.key, nginx also
#     listens on 443: set the SSL/TLS mode of the zone to "Full (strict)" (recommended);
#   - without it nginx listens on 80 only: the zone must be in "Flexible" mode.
# Run the script again after adding the certificate, to change domain, or to refresh the list of
# Cloudflare addresses.
set -euo pipefail

DOMAIN="${1:?Usage: setup-nginx.sh <domain>}"
APP_PORT="${APP_PORT:-4321}"
PRODUCTION_DOMAIN="www.adoptii-animale-hope.org"
CERT_DIR="${CERT_DIR:-/etc/ssl/hope}"

[ "$(id -u)" -eq 0 ] || { echo "Run this script as root." >&2; exit 1; }

# --- Cloudflare address ranges -----------------------------------------------------------------
RANGES="$( (curl -fsS https://www.cloudflare.com/ips-v4; echo; curl -fsS https://www.cloudflare.com/ips-v6) | grep -E '^[0-9a-fA-F.:]+/[0-9]+$' || true)"
[ "$(printf '%s\n' "$RANGES" | wc -l)" -ge 10 ] || { echo "Could not fetch the Cloudflare address ranges." >&2; exit 1; }

{
  echo "# Generated by deploy/setup-nginx.sh on $(date -u +%F). Do not edit: run the script again."
  echo
  echo "# The visitor's address is the one Cloudflare reports, for connections coming from Cloudflare."
  printf '%s\n' "$RANGES" | sed 's/.*/set_real_ip_from &;/'
  echo "real_ip_header CF-Connecting-IP;"
  echo
  echo "# 1 when the connection really comes from Cloudflare (or from the server itself)."
  echo "geo \$realip_remote_addr \$hope_from_cloudflare {"
  echo "  default 0;"
  echo "  127.0.0.1 1;"
  echo "  ::1 1;"
  printf '%s\n' "$RANGES" | sed 's/.*/  & 1;/'
  echo "}"
  echo
  echo "# Protocol used by the visitor: Cloudflare gives it in X-Forwarded-Proto."
  echo "map \$http_x_forwarded_proto \$hope_proto {"
  echo "  default \$scheme;"
  echo "  https https;"
  echo "  http http;"
  echo "}"
} > /etc/nginx/conf.d/hope-cloudflare.conf

# --- Site ---------------------------------------------------------------------------------------
if [ -s "$CERT_DIR/origin.pem" ] && [ -s "$CERT_DIR/origin.key" ]; then
  chmod 600 "$CERT_DIR/origin.key"
  TLS=1
  # The http2 directive replaced the listen parameter in nginx 1.25.1.
  NGINX_VERSION="$(nginx -v 2>&1 | sed 's#.*/##')"
  if [ "$(printf '%s\n' 1.25.1 "$NGINX_VERSION" | sort -V | head -n 1)" = 1.25.1 ]; then
    H2_PARAM="" H2_DIRECTIVE="  http2 on;"
  else
    H2_PARAM=" http2" H2_DIRECTIVE=""
  fi
  LISTEN_TLS="  listen 443 ssl$H2_PARAM;
  listen [::]:443 ssl$H2_PARAM;
$H2_DIRECTIVE
  ssl_certificate $CERT_DIR/origin.pem;
  ssl_certificate_key $CERT_DIR/origin.key;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_session_cache shared:hope:10m;"
  DEFAULT_TLS="  listen 443 ssl$H2_PARAM default_server;
  listen [::]:443 ssl$H2_PARAM default_server;
  ssl_reject_handshake on;"
else
  TLS=0
  LISTEN_TLS=""
  DEFAULT_TLS=""
fi

# Anything but the production domain is a test copy: keep it out of search engines.
if [ "$DOMAIN" = "$PRODUCTION_DOMAIN" ]; then
  ROBOTS=""
else
  ROBOTS='  add_header X-Robots-Tag "noindex, nofollow" always;'
fi

# The bare domain answers with a redirect to www.
APEX_SERVER=""
if [ "${DOMAIN#www.}" != "$DOMAIN" ]; then
  APEX_SERVER="
server {
  listen 80;
  listen [::]:80;
$LISTEN_TLS
  server_name ${DOMAIN#www.};
  if (\$hope_from_cloudflare = 0) { return 444; }
  return 301 https://$DOMAIN\$request_uri;
}
"
fi

cat > /etc/nginx/sites-available/hope <<NGINX
# Generated by deploy/setup-nginx.sh on $(date -u +%F). Do not edit: run the script again.

# Requests for any other host name, or by IP address, are dropped.
server {
  listen 80 default_server;
  listen [::]:80 default_server;
$DEFAULT_TLS
  server_name _;
  return 444;
}
$APEX_SERVER
server {
  listen 80;
  listen [::]:80;
$LISTEN_TLS
  server_name $DOMAIN;

  # Only Cloudflare may reach the site: the headers below are trusted for that reason.
  if (\$hope_from_cloudflare = 0) { return 444; }
  if (\$hope_proto = http) { return 301 https://\$host\$request_uri; }

  add_header Strict-Transport-Security "max-age=31536000" always;
$ROBOTS

  # Contact form: one attachment of 5 MB at most. Between that and this limit the site answers
  # with its own page and message; above it nginx answers a bare 413.
  client_max_body_size 8m;

  gzip on;
  gzip_proxied any;
  gzip_min_length 1024;
  gzip_types text/css text/plain text/xml application/javascript application/json application/xml application/rss+xml image/svg+xml;

  proxy_http_version 1.1;
  proxy_set_header Connection "";
  proxy_set_header Host \$host;
  # Astro builds the request URL from these two (hosts accepted: security.allowedDomains in
  # astro.config.ts) and takes the visitor's address from the first value of X-Forwarded-For,
  # so that header is replaced, never extended.
  proxy_set_header X-Forwarded-Host \$host;
  proxy_set_header X-Forwarded-Proto \$hope_proto;
  proxy_set_header X-Forwarded-For \$remote_addr;
  proxy_read_timeout 120s;

  location / {
    proxy_pass http://127.0.0.1:$APP_PORT;
  }

  # Admin: photos (15 MB each) and a video (80 MB) in one form, which refuses a selection above
  # 95 MB (MAX_UPLOAD_BYTES). Cloudflare itself refuses requests above 100 MB on the Free and Pro plans.
  location /admin {
    client_max_body_size 100m;
    proxy_request_buffering off;
    proxy_read_timeout 300s;
    proxy_pass http://127.0.0.1:$APP_PORT;
  }
}
NGINX

ln -sfn /etc/nginx/sites-available/hope /etc/nginx/sites-enabled/hope
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

echo
echo "nginx serves $DOMAIN from 127.0.0.1:$APP_PORT."
if [ "$TLS" = 1 ]; then
  echo "Origin certificate found: set the Cloudflare SSL/TLS mode to \"Full (strict)\"."
else
  echo "No origin certificate in $CERT_DIR: port 80 only, the Cloudflare SSL/TLS mode must be \"Flexible\"."
  echo "For \"Full (strict)\": create an Origin Certificate in Cloudflare (SSL/TLS > Origin Server),"
  echo "save it as $CERT_DIR/origin.pem and $CERT_DIR/origin.key, then run this script again."
fi
[ "$DOMAIN" = "$PRODUCTION_DOMAIN" ] || echo "Test domain: every answer carries X-Robots-Tag noindex. Set SITE_URL=https://$DOMAIN in shared/.env and redeploy."
